# Generated by Django 3.0.2 on 2020-01-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('lunch', models.BooleanField(default=False)),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('int_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Interior Hours')),
                ('ext_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Exterior Hours')),
                ('sick_day', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
