# Generated by Django 3.0.2 on 2020-01-16 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecard', to=settings.AUTH_USER_MODEL),
        ),
    ]
